### ISSUE TITLE
Listing_04_25: Objektname und Objektzugriffsname unterscheiden sich

### ISSUE THREAD

**Issue by name024** [cleancoderocker/webhandbuch#2]
Das JavaSkript Beispiel unter "Listing_04_25" funktioniert nicht. 
Das Objekt wird unter dem Namen "book" erzeigt. Der Zugriff des Objekts wird jedoch über den Namen "item" gemacht. 

Verbesserungsvorschlag:

```
const book = {
    title: 'Schrödinger programmiert Java',
    price: 44.90,
    author: 'Philip Ackermann',
    isbn: '978-3836245838978-3836245838',
    printDescription() {
        console.log(`${this.author}: ${this.title}`);
    }
}
console.log(book.title);   // "Schrödinger programmiert Java"
console.log(book.price);   // 44.90
console.log(book.author);  // "Philip Ackermann"
console.log(book.isbn);    // "978-3836245838"
book.printDescription();   // "Philip Ackermann: Schrödinger programmiert Java"
```

**Comment by cleancoderocker** [comment]
Danke für die Rückmeldung! 😊 Ist jetzt behoben.

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
titusz, @AwakeLithiumFlower, @MattMattV, @raw34, @shogochiai, @sandywalls, @Chas989x, @tungd, @yungfred, @miuc, @DenStanislavskyi, @sham789, @huanbd, @Arul-, @nikolobok, @shortyminingmybussiness, @bigteamkr, @jxzsxsp, @wxcsdb88, @eric-leihe, @quyctd, @si618, @ichigomiruku, @VeqsaGit, @yesvods, @alaanescobedo, @mchl18, @joshstevens19, @vxrz, @Teslow, @freedyc, @claretnnamocha, @woshicby, @codepandy, @SeungWookHan, @Desgard, @MateusMo, @bano-kauser, @shaolongcai, @hongshibao, @YBiryukov, @JaneConan, @sleeptillseven, @FelicePollano, @francofabio, @hundredlee, @Sunilrai486, @bnhansn, @definitiontv, @KnoxMajor
